let constant = {
  type: "seeAllRestaurants",
  data: {
    title: "SEE ALL",
    totalOpenRestaurants: 719,
    cards: [
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "408871",
          name: "Nayi Dilli Ke Paranthe",
          uuid: "2e3fd131-5a83-4249-8e3f-f71af7158043",
          city: "10459",
          area: "Sector 50",
          totalRatingsString: "500+ ratings",
          cloudinaryImageId: "zk259u3lq1nokmy2fego",
          cuisines: ["North Indian", "Indian", "Tandoor"],
          tags: [],
          costForTwo: 25000,
          costForTwoString: "₹250 FOR TWO",
          deliveryTime: 44,
          minDeliveryTime: 40,
          maxDeliveryTime: 50,
          slaString: "40-50 MINS",
          lastMileTravel: 6.900000095367432,
          slugs: {
            restaurant: "nayi-dilli-ke-paranthe-sector-50-sector-50",
            city: "noida-1",
          },
          cityState: "10459",
          address:
            "Kitchen No 3-4, 1st Floor, Sunder Complex, Hanuman Marg, Sarfabad, Sector 73, Noida, UP 201304",
          locality: "Hanuman Marg",
          parentId: 10616,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "30% off",
            shortDescriptionList: [
              {
                meta: "30% off | Use PARTY",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "30% off | Use code PARTY",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "30% OFF",
            shortDescriptionList: [
              {
                meta: "Use PARTY",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "30% off | Use code PARTY",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          ribbon: [
            {
              type: "PROMOTED",
            },
          ],
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID:
            "cid=5693954~p=1~eid=00000185-94c8-597c-1a3b-835700af0142",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "6.9 kms",
          hasSurge: false,
          sla: {
            restaurantId: "408871",
            deliveryTime: 44,
            minDeliveryTime: 40,
            maxDeliveryTime: 50,
            lastMileTravel: 6.900000095367432,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: true,
          avgRating: "4.0",
          totalRatings: 500,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "579096",
          name: "EatFit",
          uuid: "db7173c6-f0f8-4c80-9409-1655413da39d",
          city: "10459",
          area: "GAUTAM BUDDHA NAGAR",
          totalRatingsString: "500+ ratings",
          cloudinaryImageId: "txl997mfnzibfiuvzk92",
          cuisines: [
            "Healthy Food",
            "Pizzas",
            "North Indian",
            "Thalis",
            "Biryani",
            "Chinese",
          ],
          tags: [],
          costForTwo: 27000,
          costForTwoString: "₹270 FOR TWO",
          deliveryTime: 19,
          minDeliveryTime: 19,
          maxDeliveryTime: 19,
          slaString: "19 MINS",
          lastMileTravel: 0.8999999761581421,
          slugs: {
            restaurant: "eatfit-sector-63-sector-64",
            city: "noida-1",
          },
          cityState: "10459",
          address:
            "C-86, FIRST FLOOR, SECTOR-63 NOIDA, GAUTAM BUDDHA NAGAR, NOIDA CITY ZONE-1, Gautam Buddha Nagar , Uttar Pradesh, 201301",
          locality: "SECTOR-63",
          parentId: 76139,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
              {
                meta: "50% off | Use GUILTFREEJAN",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹150 | Use code GUILTFREEJAN",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "50% OFF",
            shortDescriptionList: [
              {
                meta: "Use GUILTFREEJAN",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹150 | Use code GUILTFREEJAN",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "0.8 kms",
          hasSurge: false,
          sla: {
            restaurantId: "579096",
            deliveryTime: 19,
            minDeliveryTime: 19,
            maxDeliveryTime: 19,
            lastMileTravel: 0.8999999761581421,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.0",
          totalRatings: 500,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "579094",
          name: "Home Plate by EatFit",
          uuid: "da0257d6-afec-4919-bf1a-d3bc8527e9cc",
          city: "10459",
          area: "GAUTAM BUDDHA NAGAR",
          totalRatingsString: "50+ ratings",
          cloudinaryImageId: "lo2yvwi4oyjcgqvlqozm",
          cuisines: [
            "Home Food",
            "North Indian",
            "Healthy Food",
            "Thalis",
            "Desserts",
            "Indian",
            "Punjabi",
          ],
          tags: [],
          costForTwo: 16000,
          costForTwoString: "₹160 FOR TWO",
          deliveryTime: 19,
          minDeliveryTime: 19,
          maxDeliveryTime: 19,
          slaString: "19 MINS",
          lastMileTravel: 0.8999999761581421,
          slugs: {
            restaurant: "home-plate-by-eatfit-sector-63-sector-64",
            city: "noida-1",
          },
          cityState: "10459",
          address:
            "C-86, FIRST FLOOR, SECTOR-63 NOIDA, GAUTAM BUDDHA NAGAR, NOIDA CITY ZONE-1, Gautam Buddha Nagar , Uttar Pradesh, 201301",
          locality: "SECTOR-63",
          parentId: 301197,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
              {
                meta: "50% off | Use GUILTFREEJAN",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹125 | Use code GUILTFREEJAN",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "50% OFF",
            shortDescriptionList: [
              {
                meta: "Use GUILTFREEJAN",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹125 | Use code GUILTFREEJAN",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "0.8 kms",
          hasSurge: false,
          sla: {
            restaurantId: "579094",
            deliveryTime: 19,
            minDeliveryTime: 19,
            maxDeliveryTime: 19,
            lastMileTravel: 0.8999999761581421,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.1",
          totalRatings: 50,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "20782",
          name: "Chaayos Chai+Snacks=Relax",
          uuid: "8b4767bd-1603-4193-bb1d-a669a8d810ab",
          city: "10459",
          area: "Gautam Buddha Nagar",
          totalRatingsString: "100+ ratings",
          cloudinaryImageId: "a9tw1grfeneeoggchz6e",
          cuisines: [
            "Bakery",
            "Beverages",
            "Chaat",
            "Desserts",
            "Home Food",
            "Italian",
            "Maharashtrian",
            "Snacks",
            "Street Food",
            "Sweets",
          ],
          tags: [],
          costForTwo: 25000,
          costForTwoString: "₹250 FOR TWO",
          deliveryTime: 25,
          minDeliveryTime: 25,
          maxDeliveryTime: 25,
          slaString: "25 MINS",
          lastMileTravel: 1.399999976158142,
          slugs: {
            restaurant: "chaayos-sector-62-indirapuram",
            city: "noida-1",
          },
          cityState: "10459",
          address:
            "Unit No-02, LGF, Hush Food Mall, H 1-A 41, 42, 43, 44, Sector--63, Noida, NOIDA CITY ZONE-1, Gautam Buddha Nagar , Uttar Pradesh-211308",
          locality: "Hush Food Mall",
          parentId: 281782,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "Flat ₹200 off",
            shortDescriptionList: [
              {
                meta: "Flat ₹200 off on orders above ₹1100.",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "Flat ₹200 off on orders above ₹1100 | Use code FLAT200",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "₹200 OFF",
            shortDescriptionList: [
              {
                meta: "Use FLAT200",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "Flat ₹200 off on orders above ₹1100 | Use code FLAT200",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          ribbon: [
            {
              type: "PROMOTED",
            },
          ],
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID:
            "cid=5699171~p=4~eid=00000185-94c8-597c-1a3b-835800af0422",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "1.3 kms",
          hasSurge: false,
          sla: {
            restaurantId: "20782",
            deliveryTime: 25,
            minDeliveryTime: 25,
            maxDeliveryTime: 25,
            lastMileTravel: 1.399999976158142,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: true,
          avgRating: "4.1",
          totalRatings: 100,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "387875",
          name: "Bake Innovate",
          uuid: "bc052a86-e79d-4b13-94e0-95e40c23aee3",
          city: "10459",
          area: "Sector 18",
          totalRatingsString: "100+ ratings",
          cloudinaryImageId: "julctxazn0y2oy6mgkeq",
          cuisines: ["Bakery", "Desserts"],
          tags: [],
          costForTwo: 35000,
          costForTwoString: "₹350 FOR TWO",
          deliveryTime: 20,
          minDeliveryTime: 20,
          maxDeliveryTime: 20,
          slaString: "20 MINS",
          lastMileTravel: 0.800000011920929,
          slugs: {
            restaurant: "bake-innovate-sector-18-sector-18",
            city: "noida-1",
          },
          cityState: "10459",
          address: "B-22, Sector 64, Noida Noida City Zone -2      201301",
          locality: "Sector 64",
          parentId: 241623,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "45% off",
            shortDescriptionList: [
              {
                meta: "45% off on all orders",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
              {
                meta: "FREE DELIVERY",
                discountType: "FREE_DELIVERY",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "45% off on all orders",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
              {
                meta: "FREE DELIVERY",
                discountType: "FREE_DELIVERY",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "45% OFF",
            shortDescriptionList: [
              {
                meta: "Free Delivery",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "45% off on all orders",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
              {
                meta: "FREE DELIVERY",
                discountType: "FREE_DELIVERY",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "0.8 kms",
          hasSurge: false,
          sla: {
            restaurantId: "387875",
            deliveryTime: 20,
            minDeliveryTime: 20,
            maxDeliveryTime: 20,
            lastMileTravel: 0.800000011920929,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.2",
          totalRatings: 100,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "66117",
          name: "Foodiness",
          uuid: "07bd18b8-1777-49cc-9a97-9c304403aa9e",
          city: "10459",
          area: "Noida 1",
          totalRatingsString: "500+ ratings",
          cloudinaryImageId: "oddshcgffo1j9fjo16ta",
          cuisines: ["North Indian"],
          tags: [],
          costForTwo: 18000,
          costForTwoString: "₹180 FOR TWO",
          deliveryTime: 21,
          minDeliveryTime: 21,
          maxDeliveryTime: 21,
          slaString: "21 MINS",
          lastMileTravel: 0.8999999761581421,
          slugs: {
            restaurant: "foodiness-knowledge-park-1-greater-noida",
            city: "noida-1",
          },
          cityState: "10459",
          address:
            "D-59, SECTOR-63, NOIDA,  Gautam Buddha Nagar , Uttar Pradesh-201301",
          locality: "Gautam Buddha Nagar",
          parentId: 13710,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "30% off",
            shortDescriptionList: [
              {
                meta: "30% off | Use JUMBO",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "30% off up to ₹150 on orders above ₹400 | Use code JUMBO",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "30% OFF",
            shortDescriptionList: [
              {
                meta: "Use JUMBO",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "30% off up to ₹150 on orders above ₹400 | Use code JUMBO",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "0.8 kms",
          hasSurge: false,
          sla: {
            restaurantId: "66117",
            deliveryTime: 21,
            minDeliveryTime: 21,
            maxDeliveryTime: 21,
            lastMileTravel: 0.8999999761581421,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.0",
          totalRatings: 500,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "458581",
          name: "Caterspoint",
          uuid: "5ff091c3-30fb-4644-8cb8-34a2bb73b692",
          city: "10459",
          area: "Sector 50",
          totalRatingsString: "500+ ratings",
          cloudinaryImageId: "zdfismlgpq8dyojmrena",
          cuisines: ["Italian", "Indian", "Salads"],
          tags: [],
          costForTwo: 60000,
          costForTwoString: "₹600 FOR TWO",
          deliveryTime: 38,
          minDeliveryTime: 35,
          maxDeliveryTime: 45,
          slaString: "35-45 MINS",
          lastMileTravel: 4.900000095367432,
          slugs: {
            restaurant: "caterspoint-sector-50-sector-50",
            city: "noida-1",
          },
          cityState: "10459",
          address:
            "Plot No 401, Fm Garden, Compound Metro Pillar No - 228, Sector 52 Gautam Buddha Nagar, Uttar Pradesh  201304",
          locality: "Fm Garden",
          parentId: 11011,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
              {
                meta: "50% off | Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "50% OFF",
            shortDescriptionList: [
              {
                meta: "Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          ribbon: [
            {
              type: "PROMOTED",
            },
          ],
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID:
            "cid=5681415~p=7~eid=00000185-94c8-597c-1a3b-835900af0704",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "4.9 kms",
          hasSurge: false,
          sla: {
            restaurantId: "458581",
            deliveryTime: 38,
            minDeliveryTime: 35,
            maxDeliveryTime: 45,
            lastMileTravel: 4.900000095367432,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: true,
          avgRating: "4.4",
          totalRatings: 500,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "579093",
          name: "Great Indian Khichdi by EatFit",
          uuid: "da2f138d-1682-4100-a4f1-c981bbf2fbed",
          city: "10459",
          area: "GAUTAM BUDDHA NAGAR",
          totalRatingsString: "100+ ratings",
          cloudinaryImageId: "laz72pf7f7b5yxn2qqm3",
          cuisines: ["Indian", "Home Food", "Healthy Food", "Snacks"],
          tags: [],
          costForTwo: 20000,
          costForTwoString: "₹200 FOR TWO",
          deliveryTime: 21,
          minDeliveryTime: 21,
          maxDeliveryTime: 21,
          slaString: "21 MINS",
          lastMileTravel: 0.8999999761581421,
          slugs: {
            restaurant: "great-indian-khichdi-by-eatfit-sector-63-sector-64",
            city: "noida-1",
          },
          cityState: "10459",
          address:
            "C-86, FIRST FLOOR, SECTOR-63 NOIDA, GAUTAM BUDDHA NAGAR, NOIDA CITY ZONE-1, Gautam Buddha Nagar , Uttar Pradesh, 201301",
          locality: "SECTOR-63",
          parentId: 319582,
          unserviceable: false,
          veg: true,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
              {
                meta: "50% off | Use GUILTFREEJAN",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹125 | Use code GUILTFREEJAN",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "50% OFF",
            shortDescriptionList: [
              {
                meta: "Use GUILTFREEJAN",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹125 | Use code GUILTFREEJAN",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "0.8 kms",
          hasSurge: false,
          sla: {
            restaurantId: "579093",
            deliveryTime: 21,
            minDeliveryTime: 21,
            maxDeliveryTime: 21,
            lastMileTravel: 0.8999999761581421,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.3",
          totalRatings: 100,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "169756",
          name: "Gaur Bikaneri",
          uuid: "97d2d357-5530-4125-903e-d952ee3d1272",
          city: "10459",
          area: "Sector 62",
          totalRatingsString: "500+ ratings",
          cloudinaryImageId: "nzwvzlmpp8efspr1svbu",
          cuisines: ["Sweets"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 22,
          minDeliveryTime: 22,
          maxDeliveryTime: 22,
          slaString: "22 MINS",
          lastMileTravel: 1.7000000476837158,
          slugs: {
            restaurant: "gaur-enterprises-dadri-tahsil-sector-64",
            city: "noida-1",
          },
          cityState: "10459",
          address:
            "SHOP NO.1 B BLOCK MARKET SEC-62 NOIDA CITY PLAZA MARKET BEHIND FORTIS HOSPITAL . DELHI",
          locality: "B BLOCK MARKET SEC-62",
          parentId: 15248,
          unserviceable: false,
          veg: true,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
              {
                meta: "50% off on all orders",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
              {
                meta: "FREE DELIVERY",
                discountType: "FREE_DELIVERY",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off on all orders",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
              {
                meta: "FREE DELIVERY",
                discountType: "FREE_DELIVERY",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "50% OFF",
            shortDescriptionList: [
              {
                meta: "Free Delivery",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off on all orders",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
              {
                meta: "FREE DELIVERY",
                discountType: "FREE_DELIVERY",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "1.7 kms",
          hasSurge: false,
          sla: {
            restaurantId: "169756",
            deliveryTime: 22,
            minDeliveryTime: 22,
            maxDeliveryTime: 22,
            lastMileTravel: 1.7000000476837158,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.3",
          totalRatings: 500,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "67594",
          name: "Leaf N Loaf",
          uuid: "63851e7f-f573-483a-8175-52687254450e",
          city: "10459",
          area: "Sector 62",
          totalRatingsString: "100+ ratings",
          cloudinaryImageId: "yuwgbtvnk2s1jkck7pjn",
          cuisines: ["Continental", "Salads"],
          tags: [],
          costForTwo: 50000,
          costForTwoString: "₹500 FOR TWO",
          deliveryTime: 23,
          minDeliveryTime: 23,
          maxDeliveryTime: 23,
          slaString: "23 MINS",
          lastMileTravel: 1.7000000476837158,
          slugs: {
            restaurant: "leaf-n-loaf-indirapuram-indirapuram",
            city: "noida-1",
          },
          cityState: "10459",
          address: "highway tower, sector 62, Noida",
          locality: "Indirapuram",
          parentId: 10154,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "40% off",
            shortDescriptionList: [
              {
                meta: "40% off | Use GUILTFREEJAN",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "40% off up to ₹120 | Use code GUILTFREEJAN",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "40% OFF",
            shortDescriptionList: [
              {
                meta: "Use GUILTFREEJAN",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "40% off up to ₹120 | Use code GUILTFREEJAN",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "1.7 kms",
          hasSurge: false,
          sla: {
            restaurantId: "67594",
            deliveryTime: 23,
            minDeliveryTime: 23,
            maxDeliveryTime: 23,
            lastMileTravel: 1.7000000476837158,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.6",
          totalRatings: 100,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "32942",
          name: "Bakingo",
          uuid: "2194bbbe-da90-423d-aad2-22ea96e276de",
          city: "10459",
          area: "Sector 64",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "hsylepkuygu6k8mryapk",
          cuisines: ["Bakery", "Desserts", "Beverages", "Snacks"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 23,
          minDeliveryTime: 23,
          maxDeliveryTime: 23,
          slaString: "23 MINS",
          lastMileTravel: 1,
          slugs: {
            restaurant: "bakingo-sector-64-indirapuram",
            city: "noida-1",
          },
          cityState: "10459",
          address:
            "B-40, Ground Floor, Sector 64, B Block, Sector 64, Noida, Uttar Pradesh 201301",
          locality: "Fortis hospital",
          parentId: 3818,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
              {
                meta: "50% off | Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "50% OFF",
            shortDescriptionList: [
              {
                meta: "Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "1 kms",
          hasSurge: false,
          sla: {
            restaurantId: "32942",
            deliveryTime: 23,
            minDeliveryTime: 23,
            maxDeliveryTime: 23,
            lastMileTravel: 1,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.3",
          totalRatings: 1000,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "583088",
          name: "Simple Burger",
          uuid: "12b65a48-9269-4596-8987-669989d3e57f",
          city: "10459",
          area: "Sector 50",
          totalRatingsString: "500+ ratings",
          cloudinaryImageId: "d3to7amcs0pu8jwauayb",
          cuisines: ["Burgers", "Snacks", "Beverages"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 37,
          minDeliveryTime: 35,
          maxDeliveryTime: 45,
          slaString: "35-45 MINS",
          lastMileTravel: 4.099999904632568,
          slugs: {
            restaurant: "simple-burger-sector-50-sector-50",
            city: "noida-1",
          },
          cityState: "10459",
          address:
            "Shop No. 2, Inside Simple Bazaar, Metro Station, Block E, Sector 51, Noida, Uttar Pradesh 201301, India",
          locality: "Inside Simple Bazaar",
          parentId: 349369,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
              {
                meta: "50% off | Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "50% OFF",
            shortDescriptionList: [
              {
                meta: "Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          ribbon: [
            {
              type: "PROMOTED",
            },
          ],
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID:
            "cid=5653696~p=13~eid=00000185-94c8-597c-1a3b-835b00af0d34",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "4 kms",
          hasSurge: false,
          sla: {
            restaurantId: "583088",
            deliveryTime: 37,
            minDeliveryTime: 35,
            maxDeliveryTime: 45,
            lastMileTravel: 4.099999904632568,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: true,
          avgRating: "4.3",
          totalRatings: 500,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "471070",
          name: "DeshiBhoj Pure Veg",
          uuid: "1560d823-ba89-45db-b07e-e38889b50940",
          city: "10459",
          area: "Sector- 66",
          totalRatingsString: "50+ ratings",
          cloudinaryImageId: "nvxptr3gsrrzifb5z0le",
          cuisines: ["North Indian", "Indian"],
          tags: [],
          costForTwo: 40000,
          costForTwoString: "₹400 FOR TWO",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          slaString: "26 MINS",
          lastMileTravel: 1.5,
          slugs: {
            restaurant: "deshibhoj-pure-veg-sector-64-sector-64",
            city: "noida-1",
          },
          cityState: "10459",
          address:
            "SHOP NO 9, STREET NO.6, KRISHNA MARKET, MAMURA SECTOR-66, NOIDA, SECTOR-66 NOIDA, NOIDA CITY ZONE-2, Gautam Buddha Nagar, Uttar pradesh-201301",
          locality: "Mamura Sector66",
          parentId: 282964,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
              {
                meta: "50% off on all orders",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
              {
                meta: "FREE DELIVERY",
                discountType: "FREE_DELIVERY",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off on all orders",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
              {
                meta: "FREE DELIVERY",
                discountType: "FREE_DELIVERY",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "50% OFF",
            shortDescriptionList: [
              {
                meta: "Free Delivery",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off on all orders",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
              {
                meta: "FREE DELIVERY",
                discountType: "FREE_DELIVERY",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "1.5 kms",
          hasSurge: false,
          sla: {
            restaurantId: "471070",
            deliveryTime: 26,
            minDeliveryTime: 26,
            maxDeliveryTime: 26,
            lastMileTravel: 1.5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.0",
          totalRatings: 50,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "579098",
          name: "Canteen Central by Eatfit",
          uuid: "0161ded6-2439-4262-8c94-a48968df0049",
          city: "10459",
          area: "GAUTAM BUDDHA NAGAR",
          totalRatingsString: "20+ ratings",
          cloudinaryImageId: "plfazfhwm2er5orbgwoy",
          cuisines: [
            "Pizzas",
            "American",
            "Pastas",
            "Fast Food",
            "Snacks",
            "Desserts",
            "Beverages",
            "North Indian",
            "Oriental",
            "Asian",
          ],
          tags: [],
          costForTwo: 25000,
          costForTwoString: "₹250 FOR TWO",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          slaString: "26 MINS",
          lastMileTravel: 0.8999999761581421,
          slugs: {
            restaurant: "canteen-central-by-eatfit-sector-63-sector-64",
            city: "noida-1",
          },
          cityState: "10459",
          address:
            "C-86, FIRST FLOOR, SECTOR-63 NOIDA, GAUTAM BUDDHA NAGAR, NOIDA CITY ZONE-1, Gautam Buddha Nagar , Uttar Pradesh, 201301",
          locality: "SECTOR-63",
          parentId: 346157,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "Flat ₹125 off",
            shortDescriptionList: [
              {
                meta: "Flat ₹125 off on orders above ₹399",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "Flat ₹125 off on orders above ₹399 | Use code FLAT125",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "₹125 OFF",
            shortDescriptionList: [
              {
                meta: "Use FLAT125",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "Flat ₹125 off on orders above ₹399 | Use code FLAT125",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "0.8 kms",
          hasSurge: false,
          sla: {
            restaurantId: "579098",
            deliveryTime: 26,
            minDeliveryTime: 26,
            maxDeliveryTime: 26,
            lastMileTravel: 0.8999999761581421,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.9",
          totalRatings: 20,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "327190",
          name: "Aggarwal Bikaneri Sweets",
          uuid: "d01a2e11-3bbd-440d-963f-a2f20b81f9e5",
          city: "10459",
          area: "Sector 74",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "oxa4uqeqhmxjd7yegzzy",
          cuisines: ["Sweets", "Snacks"],
          tags: [],
          costForTwo: 25000,
          costForTwoString: "₹250 FOR TWO",
          deliveryTime: 36,
          minDeliveryTime: 35,
          maxDeliveryTime: 45,
          slaString: "35-45 MINS",
          lastMileTravel: 6.800000190734863,
          slugs: {
            restaurant: "aggarwal-bikaneri-sweets-sector-50-sector-50",
            city: "noida-1",
          },
          cityState: "10459",
          address:
            "Kitchen No. 1, Ground Floor, Sunder Shopping Complex, Sector-73, Noida",
          locality: "Sector 50",
          parentId: 1810,
          unserviceable: false,
          veg: true,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
              {
                meta: "50% off | Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "50% OFF",
            shortDescriptionList: [
              {
                meta: "Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          ribbon: [
            {
              type: "PROMOTED",
            },
          ],
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID:
            "cid=5654017~p=16~eid=00000185-94c8-597c-1a3b-835c00af106b",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "6.8 kms",
          hasSurge: false,
          sla: {
            restaurantId: "327190",
            deliveryTime: 36,
            minDeliveryTime: 35,
            maxDeliveryTime: 45,
            lastMileTravel: 6.800000190734863,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: true,
          avgRating: "4.2",
          totalRatings: 1000,
          new: false,
        },
        subtype: "basic",
      },
    ],
    totalRestaurants: 719,
  },
};

export default constant;
